// Mouseover/ Click sound effect- by JavaScript Kit (www.javascriptkit.com)
// Visit JavaScript Kit at http://www.javascriptkit.com/ for full source code

//** Usage: Instantiate script by calling: var uniquevar=createsoundbite("soundfile1", "fallbackfile2", "fallebacksound3", etc)
//** Call: uniquevar.playclip() to play sound

var html5_audiotypes={ //define list of audio file extensions and their associated audio types. Add to it if your specified audio file isn't on this list:
	"mp3": "audio/mpeg",
	"mp4": "audio/mp4",
	"ogg": "audio/ogg",
	"wav": "audio/wav"
}

function createsoundbite(sound){
	var html5audio=document.createElement('audio')
	if (html5audio.canPlayType){ //check support for HTML5 audio
		for (var i=0; i<arguments.length; i++){
			var sourceel=document.createElement('source')
			sourceel.setAttribute('src', arguments[i])
			if (arguments[i].match(/\.(\w+)$/i))
				sourceel.setAttribute('type', html5_audiotypes[RegExp.$1])
			html5audio.appendChild(sourceel)
		}
		html5audio.load()
		html5audio.playclip=function(){
			html5audio.pause()
			html5audio.currentTime=0
			html5audio.play()
		}
		return html5audio
	}
	else{
		return {playclip:function(){throw new Error("Your browser doesn't support HTML5 audio unfortunately")}}
	}
}

//Initialize two sound clips with 1 fallback file each:

var Cat=createsoundbite("whistle.ogg", "../sonidos/Cat.ogg")
var Dog=createsoundbite("whistle.ogg", "../sonidos/Dog.ogg")
var Bull=createsoundbite("whistle.ogg", "../sonidos/Bull.ogg")
var Cow=createsoundbite("whistle.ogg", "../sonidos/Cow.ogg")
var Donkey=createsoundbite("whistle.ogg", "../sonidos/Donkey.ogg")
var Duck=createsoundbite("whistle.ogg", "../sonidos/Duck.ogg")
var Goat=createsoundbite("whistle.ogg", "../sonidos/Goat.ogg")
var Goose=createsoundbite("whistle.ogg", "../sonidos/Goose.ogg")
var Hen=createsoundbite("whistle.ogg", "../sonidos/Hen.ogg")
var Horse=createsoundbite("whistle.ogg", "../sonidos/Hose.ogg")
var Mare=createsoundbite("whistle.ogg", "../sonidos/Mare.ogg")
var Pig=createsoundbite("whistle.ogg", "../sonidos/Pig.ogg")
var Rooster=createsoundbite("whistle.ogg", "../sonidos/Rooster.ogg")
var Sheep=createsoundbite("whistle.ogg", "../sonidos/Sheep.ogg")
var Antelope=createsoundbite("whistle.ogg", "../sonidos/Antelope.ogg")
var Bat=createsoundbite("whistle.ogg", "../sonidos/Bat.ogg")
var Bear=createsoundbite("whistle.ogg", "../sonidos/Bear.ogg")
var Camel=createsoundbite("whistle.ogg", "../sonidos/Camel.ogg")
var Coyote=createsoundbite("whistle.ogg", "../sonidos/Coyote.ogg")
var Reindeer=createsoundbite("whistle.ogg", "../sonidos/Reindeer.ogg")
var Deer=createsoundbite("whistle.ogg", "../sonidos/Deer.ogg")
var Dormouse=createsoundbite("whistle.ogg", "../sonidos/Dormouse.ogg")
var Elephant=createsoundbite("whistle.ogg", "../sonidos/Elephant.ogg")
var Elk=createsoundbite("whistle.ogg", "../sonidos/Elk.ogg")
var Ferret=createsoundbite("whistle.ogg", "../sonidos/Ferret.ogg")
var Fox=createsoundbite("whistle.ogg", "../sonidos/Fox.ogg")
var Giraffe=createsoundbite("whistle.ogg", "../sonidos/Giraffe.ogg")
var Hare=createsoundbite("whistle.ogg", "../sonidos/Hare.ogg")
var Lion=createsoundbite("whistle.ogg", "../sonidos/Lion.ogg")
var Lynx=createsoundbite("whistle.ogg", "../sonidos/Lynx.ogg")
var Monkey=createsoundbite("whistle.ogg", "../sonidos/Monkey.ogg")
var Mouse=createsoundbite("whistle.ogg", "../sonidos/Mouse.ogg")
var Otter=createsoundbite("whistle.ogg", "../sonidos/Otter.ogg")
var Panther=createsoundbite("whistle.ogg", "../sonidos/Panther.ogg")
var Rabbit=createsoundbite("whistle.ogg", "../sonidos/Rabbit.ogg")
var Raccoon=createsoundbite("whistle.ogg", "../sonidos/Raccoon.ogg")
var Rhinoceros=createsoundbite("whistle.ogg", "../sonidos/Rhinoceros.ogg")
var Squirrel=createsoundbite("whistle.ogg", "../sonidos/Squirrel.ogg")
var Tiger=createsoundbite("whistle.ogg", "../sonidos/Tiger.ogg")
var Weasel=createsoundbite("whistle.ogg", "../sonidos/Weasel.ogg")
var Wildboar=createsoundbite("whistle.ogg", "../sonidos/Wildboar.ogg")
var Wolf=createsoundbite("whistle.ogg", "../sonidos/Wolf.ogg")
var Zebra=createsoundbite("whistle.ogg", "../sonidos/Zebra.ogg")
var Dolphin=createsoundbite("whistle.ogg", "../sonidos/Dolphin.ogg")
var Killerwhale=createsoundbite("whistle.ogg", "../sonidos/Killerwhale.ogg")
var Seal=createsoundbite("whistle.ogg", "../sonidos/Seal.ogg")
var Spermwhale=createsoundbite("whistle.ogg", "../sonidos/Spermwhale.ogg")
var Walrus=createsoundbite("whistle.ogg", "../sonidos/Walrus.ogg")
var Whale=createsoundbite("whistle.ogg", "../sonidos/Whale.ogg")
var Blackbird=createsoundbite("whistle.ogg", "../sonidos/Blackbird.ogg")
var Crane=createsoundbite("whistle.ogg", "../sonidos/Crane.ogg")
var Eagle=createsoundbite("whistle.ogg", "../sonidos/Eagle.ogg") 
var Falcon=createsoundbite("whistle.ogg", "../sonidos/Falcon.ogg")
var Ostrich=createsoundbite("whistle.ogg", "../sonidos/Ostrich.ogg")
var Owl=createsoundbite("whistle.ogg", "../sonidos/Owl.ogg")
var Partridge=createsoundbite("whistle.ogg", "../sonidos/Partridge.ogg")
var Penguin=createsoundbite("whistle.ogg", "../sonidos/Penguin.ogg")
var Quail=createsoundbite("whistle.ogg", "../sonidos/Quail.ogg")
var Seagull=createsoundbite("whistle.ogg", "../sonidos/Seagull.ogg")
var Sparrow=createsoundbite("whistle.ogg", "../sonidos/Sparrow.ogg")
var Swallow=createsoundbite("whistle.ogg", "../sonidos/Swallow.ogg")
var Swan=createsoundbite("whistle.ogg", "../sonidos/Swan.ogg")
var Turkey=createsoundbite("whistle.ogg", "../sonidos/Turkey.ogg")
var Vulture=createsoundbite("whistle.ogg", "../sonidos/Vulture.ogg")
var Woodpecker=createsoundbite("whistle.ogg", "../sonidos/Woodpecker.ogg")
var Anchovy=createsoundbite("whistle.ogg", "../sonidos/Anchovy.ogg")
var Barbel=createsoundbite("whistle.ogg", "../sonidos/Barbel.ogg")
var Bass=createsoundbite("whistle.ogg", "../sonidos/Bass.ogg")
var Bream=createsoundbite("whistle.ogg", "../sonidos/Bream.ogg")
var Cod=createsoundbite("whistle.ogg", "../sonidos/Cod.ogg")
var Eel=createsoundbite("whistle.ogg", "../sonidos/Eel.ogg")
var Trout=createsoundbite("whistle.ogg", "../sonidos/Trout.ogg")
var Grouper=createsoundbite("whistle.ogg", "../sonidos/Grouper.ogg")
var Herring=createsoundbite("whistle.ogg", "../sonidos/Herring.ogg")
var Salmon=createsoundbite("whistle.ogg", "../sonidos/Salmon.ogg")
var Shark=createsoundbite("whistle.ogg", "../sonidos/Shark.ogg")
var Smallhake=createsoundbite("whistle.ogg", "../sonidos/Smallhake.ogg")
var Sturgeon=createsoundbite("whistle.ogg", "../sonidos/Sturgeon.ogg")
var Crocodile=createsoundbite("whistle.ogg", "../sonidos/Crocodile.ogg")
var Lizard=createsoundbite("whistle.ogg", "../sonidos/Lizard.ogg")
var Salamander=createsoundbite("whistle.ogg", "../sonidos/Salamander.ogg")
var Smalllizard=createsoundbite("whistle.ogg", "../sonidos/Smalllizard.ogg")
var Snake=createsoundbite("whistle.ogg", "../sonidos/Snake.ogg")
var Turtle=createsoundbite("whistle.ogg", "../sonidos/Turtle.ogg")
var Viper=createsoundbite("whistle.ogg", "../sonidos/Viper.ogg")
var Frong=createsoundbite("whistle.ogg", "../sonidos/Frong.ogg")
var Ant=createsoundbite("whistle.ogg", "../sonidos/Ant.ogg")
var Bee=createsoundbite("whistle.ogg", "../sonidos/Bee.ogg")
var Beetle=createsoundbite("whistle.ogg", "../sonidos/Beetle.ogg")
var Clothesmoth=createsoundbite("whistle.ogg", "../sonidos/Clothesmoth.ogg")
var Cricket=createsoundbite("whistle.ogg", "../sonidos/Cricket.ogg")
var Dragonfly=createsoundbite("whistle.ogg", "../sonidos/Dragonfly.ogg")
var Flea=createsoundbite("whistle.ogg", "../sonidos/Flea.ogg")
var Fly=createsoundbite("whistle.ogg", "../sonidos/Fly.ogg")
var Glowworn=createsoundbite("whistle.ogg", "../sonidos/Glowworn.ogg")
var Grasshopper=createsoundbite("whistle.ogg", "../sonidos/Grasshopper.ogg")
var Horsefly=createsoundbite("whistle.ogg", "../sonidos/Horsefly.ogg")
var Ladybug=createsoundbite("whistle.ogg", "../sonidos/Ladybug.ogg")
var Louse=createsoundbite("whistle.ogg", "../sonidos/Louse.ogg")
var Mosquito=createsoundbite("whistle.ogg", "../sonidos/Mosquito.ogg")
var Plantlouse=createsoundbite("whistle.ogg", "../sonidos/Plantlouse.ogg")
var Roach=createsoundbite("whistle.ogg", "../sonidos/Roach.ogg")
var Termite=createsoundbite("whistle.ogg", "../sonidos/Termite.ogg")
var Wasp=createsoundbite("whistle.ogg", "../sonidos/Wasp.ogg")
var Caterpillar=createsoundbite("whistle.ogg", "../sonidos/Caterpillar.ogg")
var Centipede=createsoundbite("whistle.ogg", "../sonidos/Centipede.ogg")
var Hedgehog=createsoundbite("whistle.ogg", "../sonidos/Hedgehog.ogg")
var Scorpion=createsoundbite("whistle.ogg", "../sonidos/Scorpion.ogg")
var Snail=createsoundbite("whistle.ogg", "../sonidos/Snail.ogg")
var Spider=createsoundbite("whistle.ogg", "../sonidos/Spider.ogg")
var Worm=createsoundbite("whistle.ogg", "../sonidos/Worm.ogg")
var Clam=createsoundbite("whistle.ogg", "../sonidos/Clam.ogg")
var Crab=createsoundbite("whistle.ogg", "../sonidos/Crab.ogg")
var Lobster=createsoundbite("whistle.ogg", "../sonidos/Lobster.ogg")
var Oyster=createsoundbite("whistle.ogg", "../sonidos/Oyster.ogg")
var Shell=createsoundbite("whistle.ogg", "../sonidos/Shell.ogg")
var Squid=createsoundbite("whistle.ogg", "../sonidos/Squid.ogg")



